image: ralfjung/opam-ci:opam2

stages:
  - build

variables:
  CPU_CORES: "10"

.template: &template
  stage: build
  tags:
  - fp
  script:
  - git clone https://gitlab.mpi-sws.org/iris/ci.git ci -b opam2
  - ci/buildjob
  cache:
    key: "$CI_JOB_NAME"
    paths:
    - opamroot/
  only:
  - master
  - /^ci/
  except:
  - triggers
  - schedules

## Build jobs

build-coq.8.9.0:
  <<: *template
  variables:
    OPAM_PINS: "coq version 8.9.0"
    TIMING_CONF: "coq-8.9.0"
  tags:
  - fp-timing
